[package]
name = "rust-repos"
version = "0.1.0"
authors = ["Pietro Albini <pietro@pietroalbini.org>"]

[dependencies]
failure = "0.1.3"
reqwest = "0.9.5"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
log = "0.4.6"
env_logger = "0.6.0"
csv = "1.0.2"
ctrlc = "3.1.1"
crossbeam-utils = "0.5.0"
