[package]
name = "rust-repos"
version = "0.1.0"
authors = ["Pietro Albini <pietro@pietroalbini.org>"]

[dependencies]
failure = "0.1.2"
reqwest = "0.9.1"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.30"
log = "0.4.5"
env_logger = "0.5.13"
csv = "1.0.2"
ctrlc = "3.1.1"
crossbeam-utils = "0.5.0"
