[package]
name = "rust-repos"
version = "0.1.0"
authors = ["Pietro Albini <pietro@pietroalbini.org>"]

[dependencies]
failure = "0.1.5"
reqwest = "0.9.8"
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0.35"
log = "0.4.6"
env_logger = "0.6.0"
csv = "1.0.5"
ctrlc = "3.1.1"
crossbeam-utils = "0.6.3"
